/* All Apple ][e variants include a single PAL that derives clock from the
 * main 14.318MHz system clock and generates other timing-critical control
 * signals.
 *
 * Note: clocks generated by this PAL need their corresponding generated
 * clock constraints added via an SDC or XDC.  See constraints/apple_ii_pal.xdc.
 */

module AppleIIePAL(
    input clk_14M,

    output reg clk_7M,
    output clk_3_58M,
    output reg clk_q3,
    output clk_phi_0,

    // RAM address strobes
    input clk_phi_1,
    input ramen_n,
    output reg pcas_n,
    output reg pras_n,

    input vid7,
    input gr,
    input eighty_vid_n,
    input entmg,

    output h0,
    output segb,
    output ldps_n,
    output vid7m
    );

    always @(posedge clk_14M)
    clk_7M <= ~clk_7M;

    ClockDivideByN #(
        .N(14)
    ) phi_0_divider(
        .clk_in(clk_14M),
        .reset(1'b0),
        .clk_out(clk_phi_0)
    );
endmodule
